version: '3.7'

services:
  client:
    image: nginx:stable-alpine3.19-slim
    container_name: client_chat
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api_chat:v0.2
    container_name: api_chat
    ports:
      - "4040:4040"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db_chat
    ports:
      - "27017:27017"