version: '3.7'

services:
  client:
    image: nginx:stable-alpine3.19-slim
    container_name: client_chat
    ports:
      - "8080:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-chat

  api-chat:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api_chat:v0.2
    container_name: api_chat
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db_chat
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db